services:
  - type: web
    name: slidegen
    env: docker
    repo: https://github.com/kedusa/slidegen.git
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8501
